project:
  type: website
  output-dir: .

website:
  title: "CINMS-webCR ingest"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    code-fold: true
    # code-summary: "Show the code"
    code-tools: true
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left

editor: visual

