---
pagetitle: "Home | CINMS-webCR ingest"
listing:
  - id: list-datasets
    contents:
      - "datasets/*.qmd"
    type: grid
---

## Datasets

The following datasets were downloaded onto my local hard drive, which is synchronized to [sbc-mbon - Google Drive](https://drive.google.com/drive/folders/1SHmIS4YWPCKoenSHe-F0IwQYUptEaDQS).

+----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------+--------------------------------------------------------------------------------------------------------+
| **Name**                                                 | **EDI dataset**                                                                                                                                       | **EDI filename**     | **CINMS page**                                                                                         |
+==========================================================+=======================================================================================================================================================+======================+========================================================================================================+
| Kelp canopy biomass                                      | [74](https://portal.edirepository.org/nis/mapbrowse?scope=knb-lter-sbc&identifier=74)                                                                 | \                    | [kelp-canopy](https://noaa-onms.github.io/cinms/modals/kelp-canopy.html)                               |
+----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------+--------------------------------------------------------------------------------------------------------+
| Abalone                                                  | [6](https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=6);[7](https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=7) | \                    | [abalone](https://noaa-onms.github.io/cinms/modals/abalone.html)                                       |
+----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------+--------------------------------------------------------------------------------------------------------+
| Deeper water fish-effective number of species            | [110](https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=110)                                                                        | deep_fish.csv        | [biodiversity_deep-seafloor](https://noaa-onms.github.io/cinms/modals/biodiversity_deep-seafloor.html) |
+----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------+--------------------------------------------------------------------------------------------------------+
| Kelp forest fish - effective number of species           | [17](https://portal.edirepository.org/nis/mapbrowse?scope=knb-lter-sbc&identifier=17)                                                                 | mbon_fish.csv        | [biodiversity_kelp-forest](https://noaa-onms.github.io/cinms/modals/biodiversity_kelp-forest.html)     |
+----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------+--------------------------------------------------------------------------------------------------------+
| Bottom mobile invertebrates -effective number of species | [19](https://portal.edirepository.org/nis/mapbrowse?scope=knb-lter-sbc&identifier=19)                                                                 | mbon_invert.csv      | [biodiversity_kelp-forest](https://noaa-onms.github.io/cinms/modals/biodiversity_kelp-forest.html)     |
+----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------+--------------------------------------------------------------------------------------------------------+
| Sheephead LTER trend                                     | [17](https://portal.edirepository.org/nis/mapbrowse?scope=knb-lter-sbc&identifier=17)                                                                 | lter_sheephead.csv   | [ca-sheephead](https://noaa-onms.github.io/cinms/modals/ca-sheephead.html)                             |
+----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------+--------------------------------------------------------------------------------------------------------+
| Sheephead PISCO/CHIS trend                               | [5](https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=5);[7](https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=7) | \                    | [ca-sheephead](https://noaa-onms.github.io/cinms/modals/ca-sheephead.html)                             |
+----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------+--------------------------------------------------------------------------------------------------------+
| Sea cucumbers SBCLTER data                               | [19](https://portal.edirepository.org/nis/mapbrowse?scope=knb-lter-sbc&identifier=19)                                                                 | lter_seacucumber.csv | [sea-cucumbers](https://noaa-onms.github.io/cinms/modals/sea-cucumbers.html)                           |
+----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------+--------------------------------------------------------------------------------------------------------+
| Sea stars                                                | [6](https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=6);[7](https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=7) | \                    | [kelp-forest_seastars](https://noaa-onms.github.io/cinms/modals/kelp-forest_seastars.html)             |
+----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------+--------------------------------------------------------------------------------------------------------+
| Sea Urchin Island vs Mainland                            | [19](https://portal.edirepository.org/nis/mapbrowse?scope=knb-lter-sbc&identifier=19)                                                                 | lter_urchin.csv      | [sea-urchins](https://noaa-onms.github.io/cinms/modals/sea-urchins.html)                               |
+----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------+--------------------------------------------------------------------------------------------------------+
| Spiny-lobster                                            | [6](https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=6);[7](https://portal.edirepository.org/nis/mapbrowse?scope=edi&identifier=7) | \                    | [spiny-lobster](https://noaa-onms.github.io/cinms/modals/spiny-lobster.html)                           |
+----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------+--------------------------------------------------------------------------------------------------------+
| Understory algae - kelp                                  | [18](https://portal.edirepository.org/nis/mapbrowse?scope=knb-lter-sbc&identifier=18)                                                                 | \                    | [understory-algae](https://noaa-onms.github.io/cinms/modals/understory-algae.html)                     |
+----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------+--------------------------------------------------------------------------------------------------------+
| Understory algae - Red algae                             | [15](https://portal.edirepository.org/nis/mapbrowse?scope=knb-lter-sbc&identifier=15)                                                                 | \                    | [understory-algae](https://noaa-onms.github.io/cinms/modals/understory-algae.html)                     |
+----------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------+--------------------------------------------------------------------------------------------------------+
